#!/usr/bin/perl
#
# Convert a file into a #defined string.
#

die("usage: $0 SYMBOLS [file(s)]\n") unless $#ARGV > 0;

# The name to define is the first command line parameter.
$symbol = $ARGV[0]; shift;

print "// This file is automatically generated - dont edit it\n";
print "#include \"Config.hpp\"\n";
print "class Config${symbol}\n";
print "{\n";
print "public:\n";
print "    Config${symbol}() { Config::instance().registerDefaultConfig(\"${symbol}\", config); }\n";
print "    static Config${symbol} instance;\n";
print "    static const char *config;\n";
print "};\n";
print "Config${symbol} Config${symbol}::instance;\n";
print "const char *Config${symbol}::config =\n";

while (<>)
{
    chomp;
    s/"/\\"/g;
    if (defined($last))
    {
        print "\"$last\\n\"\\\n";
    }
    $last = $_;
}

print "\"$last\\n\";\n";

exit 0;
